"""server default first five2

Revision ID: 290d8aae933f
Revises: a8a03ff7ce6b
Create Date: 2024-10-02 01:36:44.968118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '290d8aae933f'
down_revision: Union[str, None] = 'a8a03ff7ce6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'id',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text('substr(cast(gen_random_uuid() as varchar(36)), 0, 5)'),
               existing_nullable=False)
    op.alter_column('Order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('OrderItem', 'id',
               existing_type=sa.VARCHAR(length=5),
               server_default=None,
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrderItem', 'id',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text('nextval(\'"OrderItem_id_seq"\'::regclass)'),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('Order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('Order', 'id',
               existing_type=sa.VARCHAR(length=5),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
