"""add relationships and cascades to orderItem

Revision ID: d5a1e810d3ae
Revises: e0ec63dd58cf
Create Date: 2024-10-02 20:07:22.931738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a1e810d3ae'
down_revision: Union[str, None] = 'e0ec63dd58cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
