"""server default first five with callables

Revision ID: e0ec63dd58cf
Revises: 290d8aae933f
Create Date: 2024-10-02 01:52:51.787660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0ec63dd58cf'
down_revision: Union[str, None] = '290d8aae933f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'id',
               existing_type=sa.VARCHAR(length=5),
               server_default=None,
               existing_nullable=False)
    op.alter_column('Order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('Order', 'id',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text('substr(((gen_random_uuid())::character varying(36))::text, 0, 5)'),
               existing_nullable=False)
    # ### end Alembic commands ###
